DEVICE_ID = "test_dht22"
RUN_MODE = "range_test"

WIFI_SSID = "YOUR_WIFI_SSID"
WIFI_PASSWORD = "YOUR_WIFI_PASSWORD"
WINDOWS_SERVER_LAN_IP = "192.168.1.50"
SERVER_URL = "http://%s:5105/api/v1/readings" % WINDOWS_SERVER_LAN_IP
TEMP_WINDOWS_SERVER_URL = SERVER_URL

UPLOAD_INTERVAL_SECONDS = 60
RANGE_TEST_INTERVAL_SECONDS = 10
COMPONENT_TEST_INTERVAL_SECONDS = 10
WIFI_TIMEOUT_SECONDS = 15
HTTP_TIMEOUT_SECONDS = 10

DHT_PIN = 4
I2C_BUS_ID = 0
I2C_SCL_PIN = 22
I2C_SDA_PIN = 21

BH1750_ENABLED = False
BH1750_ADDR = 0x23
OLED_ENABLED = False
OLED_ADDR = 0x3C
OLED_WIDTH = 128
OLED_HEIGHT = 64
